chandrayan/chandrayan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rover import views
from . import main
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', main.mainfun, name='home'),
    url(r'^index/', views.index, name='index'),
    url(r'^harry/', main.testing, name='harry'),
    url(r'^admin/', admin.site.urls, name='adm'),
    url(r'^roverlink/', include('rover.urls')),
    url(r'^logout/$', views.user_logout,name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chandrayan/rover/urls.py
from django.conf.urls import url
from rover import views

app_name = 'suyog'


urlpatterns = [
    url(r'^$', views.roverfun, name='rovn'),
    url(r'^boostlink/', views.rovboost, name='boostn'),
    url(r'^register/$', views.register, name='register'),
    url(r'^flaplink/', views.rovflap, name='flapn'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    # url(r'^media/profile_pics/$', views.images, name='images'),

]

chandrayan/rocket/models.py
from django.db import models

# Create your models here.

chandrayan/rocket/views.py
from django.shortcuts import render

# Create your views here.

chandrayan/rover/views.py
from django.shortcuts import render
from .register import resume, UserForm, UserProfileInfoForm

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def roverfun(request):
    return render(request, "rover/rovermain.html")

# Create your views here.
def success(request):
    return render(request, "rover/successpage.html")

def rovboost(request):
    instance = resume()

    if request.method == 'POST':
        instance = resume(request.POST)

        if instance.is_valid():
            instance.save(commit=True)
            return success(request)
        else:
            print('Error form invalid')

    return render(request, "rover/booster.html", {'inject':instance})

def rovflap(request):
    return render(request, "rover/flaps.html")

def index(request):
    return render(request, "rover/index.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid()  and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, "rover/registration.html",
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account Not Active")

        else:
            print("Someone tried to login and failed!")
            print("Username:{} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request,'rover/login.html',{})

# def images(request):
#     return render(request, 'i')

chandrayan/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Chandrayan</title>
    <link rel="stylesheet" href="{% static "css/master.css" %}">
    <link rel="icon" href="static/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'home' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'index' %}">Index</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:rovn' %}">Rover</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:boostn' %}">Booster</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:flapn' %}">Flaps</a></li>
          <li><a class="navbar-link" href="{% url 'harry' %}">Success</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

chandrayan/templates/mainpage.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load my_temps %}
{% block body_block %}
<h1>Welcome to Project Chandrayan.</h1>
<p>context example limitation: {{pie}} plus {{ten}} is {{ pie|add:'10'|floatformat:2}}</p>
<p>another context example: "{{sentence|upper}}" - {{letter|upper}} = "{{sentence|kut:letter|upper}}"</p>
<img src="{% static "images/moonyan.jpg"%}" alt="no cover">
{% endblock %}



<!-- {% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="icon" href="static/favicon.ico" type="image/x-icon" />
  </head>
  <body>
    <h1>Project Chandrayan.</h1>
    <p>Go to <a href="{% url 'suyog:rovn' %}">roverlink</a>/</p>
    <p>Go to <a href="{% url 'admin:index' %}">admin</a>/</p>
  </body>
</html> -->

chandrayan/templates/rover/booster.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<form method="post">
  <h1>This is booster page.</h1>
  {{ inject.as_p }}
  {% csrf_token %}
  <input type="submit" class="btn btn-primary" value="great">
</form>
{% endblock %}



<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
        <form method="post">
          <h1>This is booster page.</h1>
          {{ inject.as_p }}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="great">
        </form>
    </div>
      </body>
</html> -->

chandrayan/templates/rover/flaps.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<h1>These are flaps</h1>
{% endblock %}

chandrayan/templates/rover/index.html
<!DOCTYPE html>
{% extends "rover/regbase.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

chandrayan/templates/rover/login.html
<!DOCTYPE html>
{% extends "rover/regbase.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form class="" action="{% url 'suyog:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password" >

    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

chandrayan/templates/rover/regbase.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'home' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'index' %}">Index</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:rovn' %}">Rover</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:boostn' %}">Booster</a></li>
          <li><a class="navbar-link" href="{% url 'suyog:flapn' %}">Flaps</a></li>
          <li><a class="navbar-link" href="{% url 'harry' %}">Success</a></li>

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li><a class="navbar-link"  href="{% url 'suyog:user_login'%}">Login</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

chandrayan/templates/rover/registration.html
<!DOCTYPE html>
{% extends "rover/regbase.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering!</h1>
  {% else %}
  <h2>Register Here!</h2>
  <h3>Fill out the form:</h3>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>

{% endblock %}

chandrayan/templates/rover/rovermain.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<h1>Booster image</h1>
<img src="{% static "images/boost.jpeg"%}" alt="no boost">
{% endblock %}


<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>boostup</title>
    <link rel="stylesheet" href="{% static "css/master.css" %}">
  </head>
    <body>
      <p>Go to <a href="{% url 'suyog:boostn' %}">boostlink</a>/</p>
      <p>Go to <a href="{% url 'suyog:flapn' %}">flaplink</a>/</p>
      <p>Go to <a href="{% url 'admin:index' %}">admin</a>/</p>
      <p>Go to <a href="{% url 'home' %}">home</a>/</p>
      <p>Go to <a href="{% url 'harry' %}">end of the links tree</a>/</p>
      <h1>Booster image</h1>
      <img src="{% static "images/boost.jpeg"%}" alt="no boost">
  </body>
</html> -->

chandrayan/templates/rover/successpage.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
  <h1>Success!</h1>
  <h2>Visit  <a href="{% url 'admin:index' %}">admin</a> </h2>
</div>
{% endblock %}


<!--
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Success!</h1>
        <h2>Visit  <a href="{% url 'admin:index' %}">admin</a> </h2>
      </div>
    </div>
      </body>
</html> -->